// Central product database
export const allProducts = [
  {
    id: 1,
    name: "Premium Cashmere Sweater",
    price: 249.99,
    image: "/luxury-cashmere-sweater.jpg",
    badge: "New",
    badgeType: "new",
    category: "sweaters",
    color: "cream",
  },
  {
    id: 2,
    name: "Silk Blend Dress",
    price: 189.99,
    image: "/elegant-silk-dress.jpg",
    badge: "Sale",
    badgeType: "sale",
    category: "dresses",
    color: "black",
  },
  {
    id: 3,
    name: "Classic Oxford Shirt",
    price: 129.99,
    image: "/oxford-shirt-men.jpg",
    category: "shirts",
    color: "white",
  },
  {
    id: 4,
    name: "Tailored Blazer",
    price: 299.99,
    image: "/tailored-blazer.jpg",
    badge: "New",
    badgeType: "new",
    category: "blazers",
    color: "navy",
  },
  {
    id: 5,
    name: "Premium Denim Jeans",
    price: 159.99,
    image: "/premium-denim-jeans.jpg",
    badge: "Sale",
    badgeType: "sale",
    category: "jeans",
    color: "blue",
  },
  {
    id: 6,
    name: "Linen Button-Up",
    price: 99.99,
    image: "/linen-button-shirt.jpg",
    category: "shirts",
    color: "beige",
  },
  {
    id: 7,
    name: "Wool Trousers",
    price: 179.99,
    image: "/wool-trousers.jpg",
    category: "pants",
    color: "charcoal",
  },
  {
    id: 8,
    name: "Vintage Leather Jacket",
    price: 399.99,
    image: "/vintage-leather-jacket.jpg",
    badge: "New",
    badgeType: "new",
    category: "jackets",
    color: "brown",
  },
]

export function getProductById(id) {
  return allProducts.find((p) => p.id === Number.parseInt(id))
}
